### ISSUE TITLE
[DX] Simplify the development workflow into a single gulp task

### ISSUE THREAD

**Issue by daggerhart** [nerdstein/nerdstein-design-library#22]
Rather than require the developer to run multiple commands, let's simplify this into a single gulp task that combines the following steps, and improves them by leveraging "watch" techniques where possible:

1. `gulp sass`
1. `php core/console --server`
1. `php core/console --generate`

An immediate improvement is to combine 2 & 3 into `php core/console --server --with-watch`. 

Another improvement would be to change 1 to suggest the default gulp task which leverages the already-existing "watch" task:  `gulp`

Resulting in:

1. `gulp`
1. `php core/console --server --with-watch`

This can be combined further by using the `gulp-shell` module, and creating a new gulp task that starts the pattern lab server as part of the default gulp task, resulting in a single command of `gulp` to handle all of the above.

**Comment by nerdstein** [comment]
This is merged, closing
