### ISSUE TITLE
Convert Sass files to partials, conform to USDS, use local images.

### ISSUE THREAD

**Issue by bixgomez** [nerdstein/nerdstein-design-library#28]
I propose that we change all the individual patterns' .scss files to partials (e.g., from filename.scss to _filename.scss), so that they can be included as part of a traditional Sass file structure, inheriting variables and mixins from a set of Sass partials outside of the _patterns directory.  This allows us to use Sass in a more efficient way -- partials are aware of the whole ecosystem, and can make use of global variables.

I also propose starting to conform to US Design Standards (fonts, colors, etc.), and using local placeholder images.

**Comment by nerdstein** [comment]
@bixgomez can you provide an update here? Please note - I don't want to use USWDS because this is my personal design

**Comment by nerdstein** [comment]
Recent pull requests suggest this can be closed, the basics are in place without the USDS work, which I did not want to explore
